client_config_backend: settings 
client_config:   
  client_id: 24303881124-5pvfqvl9b6cp410i18e706tljnq5pbin.apps.googleusercontent.com   
  client_secret: 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

save_credentials: True 
save_credentials_backend: file 
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:   
  - https://www.googleapis.com/auth/drive.file 